<?php

/**
 * @file
 * Hook implementations for Social Auth Mastodon module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_mastodon_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'social_auth_mastodon.settings_form':
      // No handbook yet, uncomment and fix a link when done
      /*
      $output = '<h3>' . t('Configuration instructions') . '</h3>';
      $output .= '<p>';
      $output .= t('Configuration instructions and other useful documentation can be found from <a href="@handbook-url">Social Auth Mastodon Handbook</a>.', ['@handbook-url' => 'https://www.drupal.org/node/2137']);
      $output .= '</p>';
      */
      break;

  }

  return $output;
}
